# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PremierSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwinjectStoryboard', '1.0.0-beta.2'
  pod 'Alamofire', '~> 4.0'
  pod 'SDWebImage', '~>3.8'


  target 'PremierSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
